package helloworld.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Body = 0;
  public static final int Class = 1;
  public static final int Lines = 2;
  public static final int Method = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5c6c770a80114b21L, 0xabc551afca74117fL);
    builder.put(0x16b42d394bd5d08eL, Body);
    builder.put(0x16b42d394bd69c97L, Class);
    builder.put(0x16b42d394bd5d091L, Lines);
    builder.put(0x16b42d394bd49bc0L, Method);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
